

export enum ErrorCodes {
  // Auth 
  INVALID_EMAIL = "INVALID_EMAIL",

  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",

  OTP_INVALID = "OTP_INVALID",
  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_TOO_MANY_ATTEMPTS = "OTP_TOO_MANY_ATTEMPTS",

  USER_ID_GENERATION_FAILED = "USER_ID_GENERATION_FAILED",

  // Validation
  VALIDATION_FAILED = "VALIDATION_FAILED",

  // Email
  EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED",

  // Auth
  UNAUTHORIZED = "UNAUTHORIZED",

  NOT_FOUND = "NOT_FOUND",

  // Generic
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
