

export enum ErrorCodes {
  // Auth / Registration
  REGISTRATION_TOKEN_MISSING = "REGISTRATION_TOKEN_MISSING",
  INVALID_REGISTRATION_TOKEN = "INVALID_REGISTRATION_TOKEN",
  INVALID_EMAIL = "INVALID_EMAIL",

  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  MOBILE_ALREADY_IN_USE = "MOBILE_ALREADY_IN_USE",

  OTP_INVALID = "OTP_INVALID",
  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_TOO_MANY_ATTEMPTS = "OTP_TOO_MANY_ATTEMPTS",

  USER_ID_GENERATION_FAILED = "USER_ID_GENERATION_FAILED",

  // Validation
  VALIDATION_FAILED = "VALIDATION_FAILED",

  // Email
  EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED",

  // Auth
  UNAUTHORIZED = "UNAUTHORIZED",

  NOT_FOUND = "NOT_FOUND",

  // Generic
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
