

export enum ErrorCodes {
  // Auth 
  INVALID_EMAIL = "INVALID_EMAIL",

  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  
  FAILED_TO_SEND_OTP = "FAILED_TO_SEND_OTP",
  OTP_INVALID = "OTP_INVALID",
  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_TOO_MANY_ATTEMPTS = "OTP_TOO_MANY_ATTEMPTS",
  OTP_RATE_LIMIT_EXCEEDED = "OTP_RATE_LIMIT_EXCEEDED",
  
  LOGIN_RATE_LIMIT_EXCEEDED = "LOGIN_RATE_LIMIT_EXCEEDED",

  USER_ID_GENERATION_FAILED = "USER_ID_GENERATION_FAILED",

  // Validation
  VALIDATION_FAILED = "VALIDATION_FAILED",

  // Auth
  UNAUTHORIZED = "UNAUTHORIZED",

  NOT_FOUND = "NOT_FOUND",

  // Generic
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  ACCOUNT_BLOCKED = "ACCOUNT_BLOCKED",

}
